name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      # - name: install postgres version
      #   run: |
      #     sudo apt update
      #     sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
      #     curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      #     sudo apt update
      #     sudo apt install postgresql-17
      #     sudo systemctl start postgresql
      #     sudo systemctl enable postgresql
      #     psql --version

      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Start backend server
        working-directory: backend
        run: npm run dev &
        env:
          PGURI: ${{ secrets.PGURI }}

      - name: Cypress run
        uses: cypress-io/github-action@v6
        continue-on-error: true
        env:
          PGURI: ${{ secrets.PGURI }}
        with:
          working-directory: frontend
          build: npm run build
          start: npm run dev

      - name: Run component tests
        working-directory: frontend
        run: npx cypress run --component

      - name: Update code coverage badge
        working-directory: frontend
        run: npx update-badge

      - name: Generate merged coverage
        working-directory: frontend
        run: |
          mkdir -p coverage/html coverage/temp
          npx nyc merge .nyc_output coverage/temp/merged.json
          npx nyc report --reporter=html --report-dir=coverage/html --temp-dir=coverage/temp

      - name: Upload code coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./frontend/coverage/html

      - name: Mirror frontend README to root
        run: cp frontend/README.md README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
