name: Cypress Tests

on: push

jobs:
  backend:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Start backend server
        working-directory: backend
        env:
          PGURI: ${{ secrets.PGURI }}
        run: |
          npm run dev &
          npx wait-on http://localhost:9999

  cypress-tests:
    runs-on: ubuntu-24.04
    needs: backend
    steps:
      - uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          build: npm run build
          start: npm run dev

      - name: Generate merged coverage
        working-directory: frontend
        run: |
          npx nyc report --reporter=lcov --report-dir coverage-merged

      - name: Upload code coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./frontend/coverage-merged

  update-badge:
    runs-on: ubuntu-24.04
    needs: cypress-tests
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Update code coverage badge
        working-directory: frontend
        run: npx update-badge

      - name: Mirror frontend README to root
        run: cp frontend/README.md README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
